/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Armchair.glb --transform 
Files: ./public/Armchair.glb [5.28MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/react-3D/cd25_website/Armchair-transformed.glb [1.59MB] (70%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

// Determine the model URL based on the environment
const isDevelopment = import.meta.env.DEV;
const localModelUrl = "/models/Armchair-transformed.glb";
const remoteModelUrl =
  "https://files.creative-directors.com/creative-website/creative25/glbs/Armchair-transformed.glb"; // Corrected remote URL if needed
const modelUrl = isDevelopment ? localModelUrl : remoteModelUrl;

console.log(`Loading model from: ${modelUrl}`); // Log which URL is being used

export function Armchair(props) {
  const { nodes, materials } = useGLTF(modelUrl);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Wide_cloth_arm_chair.geometry}
        material={materials["Wide cloth chair.001"]}
      />
    </group>
  );
}

useGLTF.preload(modelUrl);
