/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Armchair.glb --transform 
Files: ./public/Armchair.glb [5.28MB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/react-3D/cd25_website/Armchair-transformed.glb [1.59MB] (70%)
*/

import React from "react";
import { useModelLoader, preloadModel } from './utils/ModelLoader';

// Define model URLs
const localModelUrl = "/models/Armchair-transformed.glb";
const remoteModelUrl = "https://files.creative-directors.com/creative-website/creative25/glbs/Armchair-transformed.glb";

export function Armchair(props) {
  const { nodes, materials } = useModelLoader(localModelUrl, remoteModelUrl);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Wide_cloth_arm_chair.geometry}
        material={materials["Wide cloth chair.001"]}
      />
    </group>
  );
}

// Preload the model
preloadModel(localModelUrl, remoteModelUrl);
